### ISSUE TITLE
Wallet does not see addresses nor transactions

### ISSUE THREAD

**Issue by jseibel-circle** [decred/dcrwallet#1333] opened 2018-11-30 00:23 UTC
When I create new addresses with `getnewaddress` RPC call, then immediately try to `dumpprivkey`, I get in the response:
```
"error": {
        "code": -4,
        "message": "address not found"
    },
```

However, `validateaddress` show it works, with the response:
```
"result": {
        "isvalid": true,
        "address": "Ssa3tyzqMTYFEGc14SuSeSUhDmFiv5HHv5z"
    },
```

I also don't see transactions to addresses created with `getnewaddress`. Calls to `listtransactions` will show outgoing transactions to those addresses if I send coins to them, but not the incoming ones. Doesn't `getnewaddress` add the address to the wallet?

I am creating new addresses with the gappolicy ignore. I'm also trying to generate many spare addresses, like 1000. I also tried experimenting with `dcrwallet.conf` values:
```
gaplimit=10000
addridxscanlen=10000
```

But no luck. Any ideas? This is very different from other bitcoin-like currencies that maintain the private keys.

**Comment by davecgh** [comment] 2018-11-30 00:57
I don't really work on wallet, but I can confirm the issue and probably even guess what is happening.  If you have exceeded the internal watch pool via the ignore gap policy, the wallet likely no longer thinks the address is yours.

I was able to pretty easily reproduce/verify this on simnet with the following:

```bash
for i in $(seq 1 1 30); do ./ctl getnewaddress default ignore | ./ctl validateaddress - | jq '.ismine'; done
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
null
null
null
null
...
```

@jrick should be able to get this addressed or assign it appropriately.

**Comment by jrick** [comment] 2018-11-30 14:51
The address being reported valid by validateaddress only indicates that the address is well-formed and is intended for use on the active network.  It does not indicate that the address is considered controlled by the wallet, and transactions paying to the address are going to be missed.  In order to check that the address is controlled, look for the `"ismine": true` field in the response object.

If you want to manually advance how many addresses the wallet has derived and is aware of, use the `accountsyncaddressindex` RPC.  This will allow you to manually derive additional addresses for an account's branch (either external `0` or internal `1`).

Since you are working with simnet, are you by chance calling getnewaddress before any blocks have been mined? I am able to reproduce this exact or similar bug on a fresh simnet wallet if there is no blocks in the chain other than the genesis block.

**Comment by jseibel-circle** [comment] 2018-11-30 15:12
Thank you so much for taking the time to respond, very much appreciate it.

I have about 160 blocks mined. I tried calling `accountsyncaddressindex` with parameters `["default", 0, 1000]` and `["default", 1, 1000]` to allocate 1000 addresses for both external and internal. (Question - what is the difference between these? Internal can only be used for transactions among addresses inside the wallet?)

Once I call this, I use `getnewaddress` with parameters `["default", "ignore"]` and then `dumpprivkey` fails for the new address and `validateaddress` doesn't have it.

However, if I use `importprivkey` the wallet will track the imported address fine, with proper responses to `validateaddress` with all the metadata.

Is there something I'm missing here? I just want to be able to add new addresses to the wallet, track transactions to them, and be able to dump the private key for the new address.

**Comment by davecgh** [comment] 2018-11-30 17:53
To answer your questions, external is used for addresses that you hand out externally, internal is for change addresses.  The wallet watches both.

You should be able to do what you suggest regarding adding new addresses, and the linked PR #1334 resolves that issue.

**Comment by jseibel-circle** [comment] 2018-11-30 17:59
Just to clarify, I shouldn't need to use `accountsyncaddressindex` after this fix, yes? The purpose of that call is to mass generate N addresses, whereas `getnewaddress` just does a single one?

Or what is the purpose of `accountsyncaddressindex` otherwise? I can't find clear doc on this API

**Comment by davecgh** [comment] 2018-11-30 18:13
Typically, you should not need to use `accountsyncaddressindex`, particularly if you just generated the addresses.

The only time you would really want/need to use it is if you ended up generating a really large number of unused addresses and you are restoring a wallet from seed without also wanting to update the gap limit for memory usage reasons.  In that case, if you know your last generated address index before you perform the restore, you can manually advance the index to that point and then perform a rescan to effectively bypass the default logic which automatically tries to find your most recently used address.

**Closed** 2018-11-30 18:37 UTC
Labels: bug
