### ISSUE TITLE
cold wallet missed vote count includes votes created by hot wallet

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#903] opened 2017-08-15 18:21 UTC
Setup: "cool" staking (solo, with one wallet to purchase tickets delegated to a second wallet).
Running on dcrwallet master, with the new stake manager from jrick.

Issue: The voted count is correct on the hot wallet, which only votes and has spendable balance.  But the cold wallet, when sync'd, shows that same count as the number of missed.

rescanwallet does not change anything.  The cold wallet can gettransaction of the votes, but the vote count does not change.

jrick on Slack:

> anyways, for whatever reason, spend tracking seems to be missing between the ticket purchase and that vote
so wallet doesn't see that output as spent and because the ticket isn't live or expired, it must be missed
so we need to figure out why the spend tracking is not right

More details:

hot = online and voting, not buying
cold = not voting, just buying
two different seeds, of course
cold does not stay online for more than brief periods
purchaseticket is run on the cold wallet using p2pkh ticket addresses generated from the hot wallet's master pub key of default account (not getnewaddress, but I verified they match)
immaturestakegeneration changes in the cold wallet (the one that buys, does not vote, and has a large missed count), so it recognizes the stakegen output
getbalance on hot (voting) wallet: total is exactly equal to votingauthority

On a side note: I have been having major difficulty getting the live count on the hot wallet to stay up to date.  
rescanwallet from genesis helped, but not rescan from a sensible height before the wallet was even created.  The hot wallet seemed to fall behind somehow in the address index

**Comment by chappjc** [comment] 2017-08-16 05:45
This may or may not be related, but the following often happens when purchasing more than once at a given height:

    -4: failed to send split transaction: -32603: orphan transaction [id1] references outputs of unknown or fully-spent transaction [id2

waiting for a block to be mined may delay the error further, but a rescanwallet is the only solution

**Comment by raedah** [comment] 2017-08-16 20:28
This looks like it may be a dup of https://github.com/decred/dcrwallet/issues/849 which was fixed by https://github.com/decred/dcrwallet/pull/886

**Comment by chappjc** [comment] 2017-08-16 20:46
This was running in master after that PR was merged.  I can try with today's master, but it's something else I think

**Comment by chappjc** [comment] 2017-08-21 05:54
Here's another issue I noticed in this setup.  The cold wallet that does not own the ticket addresses also tries to sign votes (if one happens to be called when it's online for purchasing).

    [ERR] WLLT: Failed to sign vote for ticket hash [ticket hash]: failed to fetch address '[ticket address]': address not found

The ticket address is owned by the hot wallet, which did vote on it successfully.

**Comment by chappjc** [comment] 2017-08-22 08:06
Also, on cold wallet startup, if there were votes while it was offline, you get the following in dcrd's log:

    [ERR] RPCS: Tx rejected: transaction [tx id] votes on old block height of 157xxx which is before the current cutoff height of 160yyy

**Comment by jrick** [comment] 2017-08-22 20:59
Just to be clear on the expected behavior, these missed tickets are extra tickets right? since this wallet doesn't own them I don't think they should be showing up in getstakeinfo at all (or spending them).

**Comment by chappjc** [comment] 2017-08-22 21:02
Right, they are completely out of place in the cold wallet's getstakeinfo, and it should not try to redeem them.

**Comment by jrick** [comment] 2017-08-22 21:08
It probably logs after the fact on success.

**Comment by jyap808** [comment] 2017-08-23 01:44
I upgrade to 1.0.7 on dcr.ubiqsmart.com and my reported voted tickets dropped from 22468 to 21192

**Comment by jrick** [comment] 2017-08-23 14:48
@jyap808 #849

**Closed** 2017-08-23 17:00 UTC
