### ISSUE TITLE
dcrwallet displays the wrong balance during stake mining

### ISSUE THREAD

**Issue by ZeroASIC** [decred/dcrwallet#77] opened 2016-03-01 19:40 UTC
dcrwallet does not use the balancetomaintain option from the config file or the command line completely correctly.  This has been an issue for some time but has gone unreported.  The ticketmaxprice works as expected, but as soon as that condition is met the wallet grabs the entire balance to buy tickets, but doesn't buy them.

**Comment by ZeroASIC** [comment] 2016-03-01 19:45
This issue might only be cosmetic.  It shows the balance as 0 when it shouldn't.

**Comment by Retord** [comment] 2016-03-01 19:53
try doing
dcrctl -u <user> -P <pass> --wallet getbalance "default" 0 all
This will give you your total wallet balance including unconfirmed balances.
and do
dcrctl -u <user> -P <pass> --wallet getbalance "default" 0 spendable 
will give you the balance you can spend and is not being spent on buying tickets and can be sent to other wallets.

Basically once your wallet spendable balance meets the maxticketprice criteria, a ticket is bought on the new block and rest of the balance gets transferred to a new address made from your own seed, since the transaction is unconfirmed till the next block it doesn't show up when u only do get balance.

 if you restart your wallet at that point and set maxticketprice to 0.0 
from the next blockchain once the last transaction has been confirmed, your entire spendable balance will show up.

~This is basically what I noticed from my recent ticket buying adventures.
A dev can elaborate more.

**Comment by cjepson** [comment] 2016-03-02 16:00
Known issue. OP_SSTXCHANGE tagged outputs require 1-conf to spend in wallet/mempool. Both need to be refactored to allow chaining of tickets. Buying a ticket will send the remaining funds to change, so you won't see it show up in balance until getting 1-conf.

In the meantime, getbalance can be changed to show OP_SSTXCHANGE tagged amounts. The caveat is they're still unspendable, so it might confuse the user.

**Comment by cjepson** [comment] 2016-03-16 21:59
Should be fixed in #104

**Closed by cjepson** 2016-03-16 21:59 UTC
