### ISSUE TITLE
Sending all funds not possible with dcrctl

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#900] opened 2017-08-13 07:46 UTC
Using dcrctl's  sendfrom or sendtoaddress, they take an address and an amount. Since the tx requires a fee, trying to send with the max amount returns an insufficient funds error. There is no straight forward way using dcrctl to send all the funds from an account. Result is having unusable change left in an address.

**Comment by jrick** [comment] 2017-08-13 15:48
Duplicate of #733.

**Closed by jrick** 2017-08-13 15:48 UTC
Labels: duplicate
