### ISSUE TITLE
vote before connected

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#444] opened 2016-12-07 23:33 UTC
Log shows the wallet voting on the block before it connects the block, which shouldn't logically be possible. Seems the block should be connected before the voting happens.
[INF] WLLT: Voted on block 00000000000001e1...
[INF] WLLT: Connecting block 00000000000001e1...

**Comment by jrick** [comment] 2016-12-08 16:14
This appears to be related to the fact that votes are handled in a separate channel from normal block and tx processing.  There is no synchronization between the two so you could see the vote happen first, or last depending on what ends up running first.

Going to close this because this isn't actually unexpected behavior given the (odd, imho) design.

**Closed by jrick** 2016-12-08 16:14 UTC
Labels: bug
