### ISSUE TITLE
ticketaddress should be validated as multisig when pooladdress is set

### ISSUE THREAD

**Issue by jolan** [decred/dcrwallet#345] opened 2016-09-30 16:43 UTC
If someone is using a stake pool and purchases tickets and swaps the ticketaddress and pooladdress, the ticket gets delegated to the pool's fee wallet.  This should be caught.

Related to decred/paymetheus#182

**Comment by jrick** [comment] 2018-09-17 15:20
Closing with working as intended.  The client should perform extra verification if necessary.

**Closed by jrick** 2018-09-17 15:20 UTC
