### ISSUE TITLE
default should be used when an account is not specified in an rpc request

### ISSUE THREAD

**Issue by ByronAP** [decred/dcrwallet#107] opened 2016-03-12 17:09 UTC
default should be used when an account is not specified in an rpc request

ex: GetNewAddress("") should be the same as GetNewAddress("default")

re: conform to bts standard

**Comment by cjepson** [comment] 2016-03-14 19:49
That is the current way it works for getnewaddress. Which RPC commands were you referring to?

**Comment by jcvernaleo** [comment] 2016-04-04 20:53
@ByronAP as @cjepson said, I think most RPC commands do this.  Can you point out which one or ones doesn't so I can take a look at them?
Thanks!

**Comment by jcvernaleo** [comment] 2016-04-11 13:39
Since it has been about a month with no follow-up and we haven't been able to reproduce I'm closing this.  Feel free to reopen if there is still an issue.

**Closed by jcvernaleo** 2016-04-11 13:39 UTC
