### ISSUE TITLE
walletpassphrase history

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#166] opened 2016-04-07 01:17 UTC
When using the walletpassphrase cmd in the terminal, the propose the password should be automatically scrubbed from the scrollback up arrow history.

**Comment by jcvernaleo** [comment] 2016-04-07 12:46
Saving the history or not is up to the shell, not the command being run.
That being said, there are a few ways you can tell your shell not to save the history for just the current session or current command.  Assuming bash (other shells probably let you do something similar but I'm less familiar with them) you can do two things.  In my .bashrc I have a line that says:
HISTCONTROL=ignoredups:ignorespace
(I think ubuntu and debian have this by default) then if you start the command with a space it will not be saved to history:
dcrctl someopts
vs
 dcrctl someopts
Another option is to put all the commands in a shell script and run that.
Or you can turn the history off for a given session:
unset HISTFILE
Hopefully one of those options works for you.  I think letting the shell control it is a much better option than trying to hack something into the tool (which likely wouldn't be portable anyway).

**Comment by jcvernaleo** [comment] 2016-04-07 12:48
Looks like I don't know how to make github markdown show a single space at the start of a line for my example but hopefully it is still clear.

**Comment by jrick** [comment] 2016-04-07 13:03
@jcvernaleo I believe @raedah is referring to history saved while using `--terminal`, which does not use shell history.

**Comment by jcvernaleo** [comment] 2016-04-07 17:33
I see.  I thought decred/dcrd#104 was for the --terminal option and this was the cmd line but I guess not.  So isn't this a dup of the dcrd issue?

**Comment by chappjc** [comment] 2016-04-07 20:06
I think this one is for the shell commend line and the other is for --terminal.

I use `HISTCONTROL=ignoreboth` in my .bashrc, which is shorthand for what @jcvernaleo suggested.  Also, every machine I plan to use frequently gets an installation of https://github.com/dvorka/hstr

**Comment by jcvernaleo** [comment] 2016-04-08 14:42
@raedah could you clarify if this is the shell or --terminal that you are talking about?  And if it is --terminal is it a duplicate of  decred/dcrd#104 ?

**Comment by raedah** [comment] 2016-04-08 18:33
I am speaking of --terminal.  Here I am proposing that passphrases never be added to the history at all. In https://github.com/decred/dcrd/issues/104 I propose a way of clearing the history in its entirety.

**Comment by alexlyp** [comment] 2016-06-29 19:03
So this is achieve by using protected option with terminal.  When in protected mode, nothing on the command line is shown or saved in history.  That with the PR to clear the terminal is able to achieve what is asked for here.  Closing.

**Closed by alexlyp** 2016-06-29 19:03 UTC
Labels: enhancement
