### ISSUE TITLE
panic sidechain

### ISSUE THREAD

**Issue by dajohi** [decred/dcrwallet#884] opened 2017-07-29 15:01 UTC
wallet running commit fa95c93989abf8674762da12fd468f5b34c3f47a

```
2017-07-29 04:44:47.881 [INF] RPCS: RPC method stakepooluserinfo invoked by client 127.0.0.1:59406
2017-07-29 04:44:47.881 [INF] RPCS: RPC method stakepooluserinfo invoked by client 127.0.0.1:59406
2017-07-29 04:44:47.882 [INF] RPCS: RPC method stakepooluserinfo invoked by client 127.0.0.1:59406
2017-07-29 04:44:47.884 [ERR] WLLT: Failed to send revocation 2a8c751c0246c8e95c0a698f08f69f8bcd7cccadaf84bd03b53b8ea59627e096 for ticket hash 57c249d4b467c2be13e5e0087053f625100c779288ea6e78108203a93e5ea7db: -32603: transaction already exists
2017-07-29 04:44:47.884 [INF] WLLT: Adding block 00000000003f5d706ea8b032722b9823ef96fdf09a1fc534dc34d149890319e0 (height 97605) to sidechain
2017-07-29 04:44:47.897 [ERR] WLLT: Failed to send revocation 2a8c751c0246c8e95c0a698f08f69f8bcd7cccadaf84bd03b53b8ea59627e096 for ticket hash 57c249d4b467c2be13e5e0087053f625100c779288ea6e78108203a93e5ea7db: -32603: transaction already exists
2017-07-29 04:44:47.897 [INF] WLLT: Adding block 0000000003977621ad74092f42c8296a1392b6dd0155e5a5e4ead1e6361bc4b4 (height 97606) to sidechain
panic: runtime error: makeslice: len out of range

goroutine 38 [running]:
panic(0xa884a0, 0xc4204f5060)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/decred/dcrwallet/wallet.(*Wallet).switchToSideChain(0xc422250000, 0x100a780, 0xc421638200, 0x752250, 0xc4203e85a0, 0xc422696501)
        /home/dcrd/.go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:165 +0x1f3
github.com/decred/dcrwallet/wallet.(*Wallet).onBlockConnected.func1(0x100a780, 0xc421638200, 0xc421638200, 0x0)
        /home/dcrd/.go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:251 +0x4b
github.com/decred/dcrwallet/walletdb.Update(0x1008ac0, 0xc4203e85a0, 0xc423585c48, 0xc4242d8801, 0x2)
        /home/dcrd/.go/src/github.com/decred/dcrwallet/walletdb/interface.go:219 +0x6f
github.com/decred/dcrwallet/wallet.(*Wallet).onBlockConnected(0xc422250000, 0xc421b92000, 0xb4, 0xb4, 0xc4222dd950, 0x2, 0x2, 0x0, 0x0)
        /home/dcrd/.go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:253 +0x5af
github.com/decred/dcrwallet/wallet.(*Wallet).handleConsensusRPCNotifications(0xc422250000, 0xc421e8bb90)
        /home/dcrd/.go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:36 +0x3c3
github.com/decred/dcrwallet/wallet.(*Wallet).handleChainNotifications(0xc422250000, 0xc421e8bb90)
        /home/dcrd/.go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:100 +0x6a
created by github.com/decred/dcrwallet/wallet.(*Wallet).SynchronizeRPC
        /home/dcrd/.go/src/github.com/decred/dcrwallet/wallet/wallet.go:556 +0x1a1
```

**Comment by jrick** [comment] 2017-08-01 16:15
Duplicate of #525

**Closed by jrick** 2017-08-01 16:15 UTC
